# Generated by Django 5.0.2 on 2024-03-07 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loan',
            options={'ordering': ['-due_date']},
        ),
        migrations.AlterModelTable(
            name='loan',
            table=None,
        ),
    ]
