# Generated by Django 5.0.2 on 2024-03-07 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0002_alter_loan_options_alter_loan_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loantransaction',
            name='type',
        ),
    ]
