# Generated by Django 5.0.2 on 2024-03-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0003_remove_loantransaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantransaction',
            name='type',
            field=models.CharField(choices=[('REPAY', 'repay'), ('LOAN_DISBURSEMENT', 'loan_disbursement')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
