# Generated by Django 5.0.2 on 2024-03-07 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmamapesa', '0006_alter_loantransaction_type_delete_loanrepayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='purpose',
        ),
        migrations.AlterField(
            model_name='loantransaction',
            name='type',
            field=models.CharField(choices=[('LOAN_REPAYMENT', 'loan_repayment'), ('LOAN_DISBURSEMENT', 'loan_disbursement')], default='', max_length=20),
        ),
    ]
